// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBiTcC2XLjzBCYQGS_m2KbD8n9IwpZpw',
    appId: '1:826539229391:web:4a38bc1c419d4485e3b7ba',
    messagingSenderId: '826539229391',
    projectId: 'mopero-13f7a',
    authDomain: 'mopero-13f7a.firebaseapp.com',
    storageBucket: 'mopero-13f7a.firebasestorage.app',
    measurementId: 'G-E3R534MEQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVFhp_WrdIB5D-6oAjjINXhRsStixMUE',
    appId: '1:826539229391:android:a2fb1011b30d1e6ee3b7ba',
    messagingSenderId: '826539229391',
    projectId: 'mopero-13f7a',
    storageBucket: 'mopero-13f7a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuBiTcC2XLjzBCYQGS_m2KbD8n9IwpZpw',
    appId: '1:826539229391:web:ac45479e9c2d6a3ee3b7ba',
    messagingSenderId: '826539229391',
    projectId: 'mopero-13f7a',
    authDomain: 'mopero-13f7a.firebaseapp.com',
    storageBucket: 'mopero-13f7a.firebasestorage.app',
    measurementId: 'G-2VWNZMFJM0',
  );
}
